name: CI - Maven & Cucumber (Debug)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: List repo (debug)
        run: |
          echo "PWD: $(pwd)"
          ls -la
          echo "Full repo tree (first 200 lines):"
          ls -R | sed -n '1,200p'

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Show Java & Maven versions
        run: |
          java -version
          mvn -version

      - name: Run tests (maven)
        run: mvn -B test -Dheadless=true -DbaseUrl=https://www.amazon.in/
        working-directory: ./TestSuiteManagement/TestSuiteManagement

      - name: List target directory (always)
        if: always()
        run: |
          echo "Listing target directory under the module..."
          ls -la TestSuiteManagement/TestSuiteManagement/target || true
          find TestSuiteManagement/TestSuiteManagement/target -maxdepth 3 -type f -print || true

      - name: Upload test artifacts (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          path: |
            TestSuiteManagement/TestSuiteManagement/target/surefire-reports/**
            TestSuiteManagement/TestSuiteManagement/target/*.html
            TestSuiteManagement/TestSuiteManagement/target/*.xml
            TestSuiteManagement/TestSuiteManagement/target/cucumber.json
            TestSuiteManagement/TestSuiteManagement/target/allure-results/**
